// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function ConsumerCandidateMessages(arg1, arg2) {
  return window['go']['main']['App']['ConsumerCandidateMessages'](arg1, arg2);
}

export function CorePublish(arg1, arg2, arg3) {
  return window['go']['main']['App']['CorePublish'](arg1, arg2, arg3);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetMessage(arg1, arg2) {
  return window['go']['main']['App']['GetMessage'](arg1, arg2);
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetStreamDetail(arg1) {
  return window['go']['main']['App']['GetStreamDetail'](arg1);
}

export function ListAllConsumers() {
  return window['go']['main']['App']['ListAllConsumers']();
}

export function ListConsumers(arg1) {
  return window['go']['main']['App']['ListConsumers'](arg1);
}

export function ListKeyValueBuckets() {
  return window['go']['main']['App']['ListKeyValueBuckets']();
}

export function ListObjectStores() {
  return window['go']['main']['App']['ListObjectStores']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListStreams() {
  return window['go']['main']['App']['ListStreams']();
}

export function RepublishMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['RepublishMessage'](arg1, arg2, arg3);
}

export function RunNatsCLI(arg1) {
  return window['go']['main']['App']['RunNatsCLI'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function ScanMessages(arg1, arg2) {
  return window['go']['main']['App']['ScanMessages'](arg1, arg2);
}

export function ScanMessagesStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['ScanMessagesStream'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function SubscribeCore(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubscribeCore'](arg1, arg2, arg3);
}

export function UnsubscribeCore(arg1) {
  return window['go']['main']['App']['UnsubscribeCore'](arg1);
}
