// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectRequest):Promise<main.ServerInfoData>;

export function ConnectProfile(arg1:number):Promise<main.ServerInfoData>;

export function ConsumerCandidateMessages(arg1:main.ConsumerItem,arg2:number):Promise<Array<main.MessageInfo>>;

export function CorePublish(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function Disconnect():Promise<void>;

export function GetMessage(arg1:string,arg2:number):Promise<main.MessageInfo>;

export function GetServerInfo():Promise<main.ServerInfoData>;

export function GetStreamDetail(arg1:string):Promise<main.StreamDetailData>;

export function ListAllConsumers():Promise<Array<main.ConsumerItem>>;

export function ListConsumers(arg1:string):Promise<Array<main.ConsumerItem>>;

export function ListKeyValueBuckets():Promise<Array<main.BucketItem>>;

export function ListObjectStores():Promise<Array<main.BucketItem>>;

export function ListProfiles():Promise<Array<main.ProfileView>>;

export function ListStreams():Promise<Array<main.StreamItem>>;

export function RepublishMessage(arg1:string,arg2:string,arg3:Record<string, Array<string>>):Promise<void>;

export function RunNatsCLI(arg1:main.CLICommandRequest):Promise<main.CLICommandResult>;

export function SaveProfile(arg1:main.ConnectionProfile):Promise<number>;

export function ScanMessages(arg1:string,arg2:main.MessageFilters):Promise<Array<main.MessageInfo>>;

export function ScanMessagesStream(arg1:string,arg2:main.MessageFilters,arg3:string):Promise<void>;

export function Status():Promise<string>;

export function SubscribeCore(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnsubscribeCore(arg1:string):Promise<void>;
